branches:
  except:
    - /^v\d+\.\d+\.\d+/
cache:
  directories:
    - /tmp/support-firecloud.cache
    - $HOME/.local
    - $HOME/.npm
    - $HOME/.pip-cache/
    - $HOME/Library/Caches/Homebrew
    - node_modules
before_install:
  - support-firecloud/ci/linux-nosudo/bootstrap
install:
  - make deps
script:
  - make

language:
  - node_js
node_js:
  - node

dist: trusty
sudo: false

notifications:
  slack:
    rooms:
      - secure: "sX/pRnlRHRGWBPUQwdxCHR98e/pvuVXdhdpDQ6e+9z1gN6Ngt9D8iEk8nMz6BxGlqyNj8r9mrVe/jMvCkYW+EEruaH9rncDsqQgpAufHE2Wtg0uFPdzajoJltbtvD0HcofwpaU0Elm6S46+IDuYCgJ9p2oujINsWNIvTRFN8FW9p+QOP7gYWlSrkpepBgWf9oka/TS+8QjXW61F9pjkvTPMzcW+aPGQd58CkcCbbuBJzMWI+sWi/hPhFCBbdZcp1tP4L4oj/1sgxiVtTIeoTD96knEWm3sIL5dBHCgNDfKKmq8e8l8I40pB0UYfmfjGJZn0gP+Q13B53wFZFgdB/CQj/SzHCXXEYpASiZ3wsAa4lng2B3Q3vXyri4lD6CMx48llfCehv8D0A3eMTekKghu0atxbc40EuV5qM+mfi/gvNHb/eUav3poYpNk07Krri5RlXz6rEs2U77tVyc30fvBBANSz+EnaYQs+LzL+xTtlBmQ+xWmvEXufBCiSezjd8Tbi7KzkcPxDDHFHq9AlsXUj/UjY8m36lcpwyXvHDoXSznSDGZmyzmU17wMic8VFtW6qOmXbnyNQEHp5UrVfSBCX5t4GgVsPZCiWHsjFLEpj8oQAlCsBkeSaLaeDj/a6IviTuYUdbQFk5t4inRuRTMudwKgaQhIRVQ2NM/c2EMMQ=" # atex-ci
      - secure: "eJxn96/t8qbpTexugeRgKmNSTt3XZ1R0pRvFSn8gWbRMjMjCWPHKoL7DnUgCkkQYKrXnYtUZlttGL9poBMhgW5FjIq53wYKg8fCSFdi2ojkb+4nmPSFnpE8JBqr/w5WYPt+ilHFJwJD8vnBpx0nqHO72LROzStdAIm+sZNWZgOmHy0GwH61Q2c45y8w2cbnUMN/CZwzhyPr+ETENTAPBQgB+PQTQ72THzGsHwFGnjpgLD1gzn35I7uFwi2sH1o3EUwHJVtGJ8TomYqvcltMuOo6joqENSHNJ7NbibUb4TpeYju8tEyc9XAfJHGTAvzSxQpC0azSZ0PhHdaEQCQSIvh95sUbFUM/MThEkDJ4epYDTgIEBNHU17GnSftP6NirbLaVDXwm+ueLnNSCa0O/reF9KuCbHLG+eRZ9pUHdDq2PzxNkx2xQvBQ3FoLghF/lks6Ok2hczV5LtN4uVsH+B82i//XHwtYky9IRsbbxUpZl3xXAN7bOIyVqIqmAF9iL3e4FpLvsXRbokW691WHFzwZ5g8A+4zaM2aHahsUBK54sWXU6LbjjUD6iKk1fOXw6i+4VtBinz1OjhKXXHaSE3pS/kBgRtPTdxFjWEGnc8SUE/td1DQYwKEV7y/cPK6h3MB3J0b7WlSja/vOG2vwxaKtJR3R4BegijX+ohi8a2HIM=" # cloud-ci
    on_success: change
    on_pull_requests: false
